version "4.11.0"

#include "UR_Scripts/constants.zs"
#include "UR_Scripts/playerclasses.zs"
#include "UR_Scripts/systems.zs"
#include "UR_Scripts/items.zs"
#include "UR_Scripts/weapons.zs"
#include "UR_Scripts/monsters.zs"
#include "UR_Scripts/decorations.zs"
#include "UR_Scripts/HUD.zs"
#include "UR_Scripts/abilities.zs"